version: '3.8'

services:
  openfinance-participants-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OPENFINANCE_PARTICIPANTS_API_URL=https://data.directory.openbankingbrasil.org.br/participants
      - SERVER_TOMCAT_THREADS_MAX=500
      - SERVER_TOMCAT_ACCEPT_COUNT=10000
      - SERVER_TOMCAT_MAX_CONNECTIONS=10000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/participants/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'