package br.com.openfinance.service.accounts.domain.valueobject;

public enum TransactionType {
    TED,
    DOC,
    PIX,
    TRANSFERENCIA_MESMA_INSTITUICAO,
    BOLETO,
    CONVENIO_ARRECADACAO,
    PACOTE_TARIFA_SERVICOS,
    TARIFA_SERVICOS_AVULSOS,
    FOLHA_PAGAMENTO,
    DEPOSITO,
    SAQUE,
    CARTAO,
    ENCARGOS_JUROS_CHEQUE_ESPECIAL,
    RENDIMENTO_APLIC_FINANCEIRA,
    PORTABILIDADE_SALARIO,
    RESGATE_APLIC_FINANCEIRA,
    OPERACAO_CREDITO,
    OUTROS
}
