version: '3.8'

services:
  accounts-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accounts-service-vthreads
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: "--enable-preview"
      # Virtual Thread Configuration
      JDK_VIRTUAL_THREAD_SCHEDULER_PARALLELISM: "10000"
      JDK_VIRTUAL_THREAD_SCHEDULER_MAX_POOL_SIZE: "100000"
      # Database
      DB_URL: jdbc:postgresql://postgres:5432/openfinance
      DB_USERNAME: openfinance_user
      DB_PASSWORD: openfinance_pass
      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Batch Configuration
      BATCH_SIZE: 1000
      MAX_VIRTUAL_THREADS: 10000
      BATCH_TIMEOUT: 120
    depends_on:
      - postgres
      - kafka
      - redis
    networks:
      - openfinance-network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '2'

  postgres:
    image: postgres:16-alpine
    container_name: postgres-vthreads
    environment:
      POSTGRES_DB: openfinance
      POSTGRES_USER: openfinance_user
      POSTGRES_PASSWORD: openfinance_pass
      # PostgreSQL tuning for high concurrency
      POSTGRES_MAX_CONNECTIONS: 500
      POSTGRES_SHARED_BUFFERS: 256MB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openfinance-network

  redis:
    image: redis:7-alpine
    container_name: redis-vthreads
    ports:
      - "6379:6379"
    networks:
      - openfinance-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-vthreads
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - openfinance-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-vthreads
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - openfinance-network

networks:
  openfinance-network:
    driver: bridge

volumes:
  postgres_data: