package br.com.openfinance.consents.domain.entity;

public enum PermissionType {
    // Dados Cadastrais
    ACCOUNTS_READ,
    ACCOUNTS_BALANCES_READ,
    ACCOUNTS_TRANSACTIONS_READ,
    ACCOUNTS_OVERDRAFT_LIMITS_READ,

    // Cartão de Crédito
    CREDIT_CARDS_ACCOUNTS_READ,
    CREDIT_CARDS_ACCOUNTS_BILLS_READ,
    CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ,
    CREDIT_CARDS_ACCOUNTS_LIMITS_READ,
    CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ,

    // Operações de Crédito
    LOANS_READ,
    LOANS_WARRANTIES_READ,
    LOANS_SCHEDULED_INSTALMENTS_READ,
    LOANS_PAYMENTS_READ,

    // Investimentos
    BANK_FIXED_INCOMES_READ,
    CREDIT_FIXED_INCOMES_READ,
    VARIABLE_INCOMES_READ,
    FUNDS_READ,

    // Recursos
    RESOURCES_READ
}
