apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service-vthreads
  namespace: openfinance
  labels:
    app: accounts-service
    version: v2-vthreads
spec:
  replicas: 3  # Fewer replicas needed with virtual threads
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
        version: v2-vthreads
    spec:
      containers:
        - name: accounts-service
          image: openfinance/accounts-service:vthreads-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: JAVA_TOOL_OPTIONS
              value: "--enable-preview -XX:+UseZGC -XX:+ZGenerational"
            - name: JDK_VIRTUAL_THREAD_SCHEDULER_PARALLELISM
              value: "10000"
            - name: JDK_VIRTUAL_THREAD_SCHEDULER_MAX_POOL_SIZE
              value: "100000"
            - name: MAX_VIRTUAL_THREADS
              value: "10000"
            - name: BATCH_SIZE
              value: "5000"
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "4"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service-vthreads
  namespace: openfinance
spec:
  selector:
    app: accounts-service
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP

---
# HPA optimized for Virtual Threads
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: accounts-service-vthreads-hpa
  namespace: openfinance
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: accounts-service-vthreads
  minReplicas: 2  # Fewer replicas needed
  maxReplicas: 10  # Much fewer max replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Higher threshold
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85